# Base image
FROM node:alpine

# Working directory
WORKDIR /app

# Copy dependencies manifest
COPY ./package.json ./

# Install dependencies
RUN npm install

# Copy application files as a separate layer, so that dependencies are cached
COPY . .

# Run application
CMD ["npm", "start"]
